version: '3.8'

services:
  vuejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: npm run dev
